/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvRouteImport } from './routes/tv'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as AnimeRouteImport } from './routes/anime'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchTypeIdRouteImport } from './routes/watch.$type.$id'

const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeRoute = AnimeRouteImport.update({
  id: '/anime',
  path: '/anime',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchTypeIdRoute = WatchTypeIdRouteImport.update({
  id: '/watch/$type/$id',
  path: '/watch/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anime': typeof AnimeRoute
  '/movies': typeof MoviesRoute
  '/search': typeof SearchRoute
  '/tv': typeof TvRoute
  '/watch/$type/$id': typeof WatchTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anime': typeof AnimeRoute
  '/movies': typeof MoviesRoute
  '/search': typeof SearchRoute
  '/tv': typeof TvRoute
  '/watch/$type/$id': typeof WatchTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anime': typeof AnimeRoute
  '/movies': typeof MoviesRoute
  '/search': typeof SearchRoute
  '/tv': typeof TvRoute
  '/watch/$type/$id': typeof WatchTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/anime' | '/movies' | '/search' | '/tv' | '/watch/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/anime' | '/movies' | '/search' | '/tv' | '/watch/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/anime'
    | '/movies'
    | '/search'
    | '/tv'
    | '/watch/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimeRoute: typeof AnimeRoute
  MoviesRoute: typeof MoviesRoute
  SearchRoute: typeof SearchRoute
  TvRoute: typeof TvRoute
  WatchTypeIdRoute: typeof WatchTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime': {
      id: '/anime'
      path: '/anime'
      fullPath: '/anime'
      preLoaderRoute: typeof AnimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$type/$id': {
      id: '/watch/$type/$id'
      path: '/watch/$type/$id'
      fullPath: '/watch/$type/$id'
      preLoaderRoute: typeof WatchTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimeRoute: AnimeRoute,
  MoviesRoute: MoviesRoute,
  SearchRoute: SearchRoute,
  TvRoute: TvRoute,
  WatchTypeIdRoute: WatchTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
